version: '2'
services:
  aws-sam-local:
    image: cnadiminti/aws-sam-local
    command: local start-api --docker-volume-basedir "$PWD" --host 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/var/opt
    env_file:
      - .env
    links:
      - dynamodb
  dynamodb:
    image: cnadiminti/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - $PWD:/dynamodb_local_db
  node-server:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/server
    working_dir:
      /server
