version: 2
jobs:
  build:
    docker:
      - image: cnadiminti/aws-sam-local
    steps:
      - checkout
      - run: |
          sam validate ./template.yml
          sam package --template-file template.yaml --s3-bucket commute-matt-canty --output-template-file package.yaml
          sam deploy --template-file package.yaml --stack-name commute-app --capabilities CAPABILITY_IAM